"""Add percentile field in codeforces,codechef association

Revision ID: 7859cb880184
Revises: 7e75b832c694
Create Date: 2020-07-10 22:48:11.298072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7859cb880184'
down_revision = '7e75b832c694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_codechef', sa.Column('percentile', sa.Float(), nullable=True))
    op.add_column('user_codeforces', sa.Column('percentile', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_codeforces', 'percentile')
    op.drop_column('user_codechef', 'percentile')
    # ### end Alembic commands ###
