"""link users codeforces table and users codechef table

Revision ID: 7e75b832c694
Revises: f1c18585f9c2
Create Date: 2020-07-10 00:06:26.634617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e75b832c694'
down_revision = 'f1c18585f9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codechef',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contest_name', sa.String(), nullable=False),
    sa.Column('starting_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('contest_type', sa.Enum('LONG', 'COOKOFF', 'LUNCHTIME', name='codechef_types'), nullable=True),
    sa.Column('contest_status', sa.Enum('BEFORE', 'CODING', 'PENDING SYSTEM TEST', 'SYSTEM TEST', 'FINISHED', name='codechef_status_types'), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.Column('is_added', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_codechef'))
    )
    op.create_table('codeforces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_name', sa.String(), nullable=False),
    sa.Column('starting_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('contest_type', sa.Enum('CF', 'IOI', 'ICPC', name='codeforces_types'), nullable=True),
    sa.Column('contest_status', sa.Enum('BEFORE', 'CODING', 'PENDING SYSTEM TEST', 'SYSTEM TEST', 'FINISHED', name='codeforces_status_types'), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.Column('is_added', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_codeforces'))
    )
    op.create_table('user_codechef',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('codechef_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['codechef_id'], ['codechef.id'], name=op.f('fk_user_codechef_codechef_id_codechef')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_codechef_user_id_users'))
    )
    op.create_table('user_codeforces',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('codeforces_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['codeforces_id'], ['codeforces.id'], name=op.f('fk_user_codeforces_codeforces_id_codeforces')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_codeforces_user_id_users'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_codeforces')
    op.drop_table('user_codechef')
    op.drop_table('codeforces')
    op.drop_table('codechef')
    # ### end Alembic commands ###
