"""empty message

Revision ID: 82aec46c9194
Revises: bac2b39fa6ec
Create Date: 2020-06-15 14:50:50.806071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82aec46c9194'
down_revision = 'bac2b39fa6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
