"""add user table

Revision ID: 89215fcc3dad
Revises: 
Create Date: 2020-05-28 01:54:38.996484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89215fcc3dad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('class_type', sa.Enum('FE', 'SE', 'TE', 'BE', 'Other', name='class_types'), server_default='Other', nullable=True),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=False,default=0),
    sa.Column('is_active', sa.Boolean(), nullable=False,default=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False,default=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('handle', name=op.f('uq_user_handle'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
