"""empty message

Revision ID: bac2b39fa6ec
Revises: d082be5cf90e
Create Date: 2020-05-31 18:53:49.254782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bac2b39fa6ec'
down_revision = 'd082be5cf90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('contests', sa.Column('duration_seconds', sa.Integer(), nullable=False))
    op.add_column('contests', sa.Column('reverted_at', sa.DateTime(), nullable=True))
    op.drop_column('contests', 'durationSeconds')
    op.drop_column('contests', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contests', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('contests', sa.Column('durationSeconds', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('contests', 'reverted_at')
    op.drop_column('contests', 'duration_seconds')
    op.drop_column('contests', 'added_at')
    # ### end Alembic commands ###
