"""empty message

Revision ID: f1c18585f9c2
Revises: 4b532f668171
Create Date: 2020-06-30 23:45:37.554581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c18585f9c2'
down_revision = '4b532f668171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('aggr_percent', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('avg_percent', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('contests_played', sa.Integer(), nullable=True))
    op.drop_column('users', 'overall_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('overall_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'contests_played')
    op.drop_column('users', 'avg_percent')
    op.drop_column('users', 'aggr_percent')
    # ### end Alembic commands ###
